[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_pda = "A1s8FpN4ZYB4Yrh3sAPr2VroBggnx5cJ2N7cTBBjc13E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/djaciel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
